- pymake/pymake.py
Replace F90 and F90FLAGS with FC and FFLAGS, respectively, which are the normal [implicit variables for GNU Make](https://www.gnu.org/software/make/manual/html_node/Implicit-Variables.html), and used elsewhere in pymake.
Also simplify the pattern rules for building the $(PROGRAM), i.e. [the manual](https://www.gnu.org/software/make/manual/make.html) typically uses `-o $@`.
> Use modern GNU Make conventions

- examples/make_modpath7.py
This example-file compiles modpath7 correctly but leaves the binary file in the root-folder and deletes the temp folder.
In all other examples, the binary file of the compiled source code is created and left in the temp-folder.
So I'll propose, improving consistency, to do the same here.
My changes are:
* setting the target to ./temp/mf7
* remove ./temp/Modpath_7_1_000 after finishing the compilation
* do not delete the temp-folder
After this, with this oneliner all binaries can be compiled at once:
```
for file in ./examples/*; do python3 $file 2>/dev/null; done
```
> Updates make_modpath7.py to improve consistency

- autotest/t001_test.py
- autotest/t007_test.py
- pymake/pymake.py
Flags should be passed as expected by the compiler. Currently, pymake's checking/adding '-' to each fflag token is problematic for (e.g.) Intel, which can have flags with spaces like `-warn unused`. Also, compiler flags are always case-sensitive, so there's no need to do `.upper()` on these. (Also, these spaces need to be split in cmdlist to work correctly with Popen, which is done here too.)
This is a minor breaking change, in that external tools that use pymake will need to ensure the fflags have dashes, where they would normally be expected by the compiler.
There are many other changes included here (got carried away):
* `fflags` can either be a str `'-flag1 -flag two'` or list `['-flag1', '-flag two']`
* Correct ifort `-double_size` to `-double-size`, and `/real_size` to `/real-size` …
> Remove extra interpretations to fflags

- pymake/autotest.py
To make regressions tests of MF**5**/MT3D-USGS and MF**6**/MT3D-USGS easier it is handy to pull MF6 simulation files into the directory where MF5 (i.e., all MF variants prior to MF6) input is hanging out without those files being deleted.
> Modification to facilitate testing of MF6/MT3D-USGS linkage

- .gitignore
- autotest/t012_test.py
- examples/buildall.bat
- pymake/__init__.py
- pymake/build_program.py
- pymake/download.py
- pymake/pymake.py
- pymake/usgsprograms.py
- pymake/usgsprograms.txt
Add gsflow build autotest (`t012_test.py`) that includes a test run of the
sagehen model for a shortened simulation period. Update `build_apps()` to 
build single and double precision versions of targets based on the
`standard_switch` and `double_switch` columns in `usgsprograms.txt`. If 
`--appdir` command line argument is specified when running `buildall.py`
`code.json` is also copied to the specified `--appdir` directory.
> ci(gsflow): Added gsflow build autotest

- autotest/t012_test.py
- autotest/t999_test.py
- examples/buildall.bat
- examples/buildall.py
- pymake/__init__.py
- pymake/build_program.py
- pymake/download.py
- pymake/pymake.py
- pymake/usgsprograms.txt
zip_all() function to zip executables after build. Add sutra to
usgsprograms.txt
> feat(download): Add zip_all function

- autotest/t009_test.py
- autotest/t999_test.py
- pymake/usgsprograms.py
Add static method for checking current version number of a target.
> CI(mt3dusgs): Add version check in mt3dusgs test

- pymake/pymake_build_apps.py
Regardless of the `download_directory` given by the user it is always set to `'temp'`. With the proposed changes the `download_directory` is only set to `'temp'` if not defined by user (`None`).
> only set download directory to 'temp' if it is None

- pymake/autotest/autotest.py
These changes shouldn't change anything, since types like `np.float` are alias to builtin `float` types. These alias are deprecated as of [numpy 1.20](https://numpy.org/doc/stable/release/1.20.0-notes.html#using-the-aliases-of-builtin-types-like-np-int-is-deprecated).
> fix(numpy): aliases of builtin types is deprecated as of numpy 1.20

- examples/make_mf2005.py
- pymake/utils/_compiler_switches.py
- pymake/utils/_usgs_src_update.py
Added src_update for pgc7.f block that causes floating inexact errors on
macos with intel ifort compiler.
> feat(switches): add support for compiler switch with spaces

- .github/workflows/pymake-linting-install.yml
- MANIFEST.in
- pymake/autotest/autotest.py
Closes #111
The issue is that the source distribution did not include the build dependencies from `pyproject.toml`.
This PR does a partial rollback of c370efa28866ce7391a7e8f1d9a14edba6682eec and does two extra checks: [build](https://github.com/pypa/build) (which would have failed before), and checks the source distribution and wheels using [twine](https://github.com/pypa/twine).
Note that two files should normally be uploaded to PyPI: a sdist (.tar.gz) and wheels (.whl). This can be done with twine.
> fix(package build): include pyproject.toml for sdist, add check

- pymake/pymake_base.py
In attempting to build on our system, we identified fc here as containing the entire path to gfortran, which caused the preprocessor directive to be set erroneously as `-fpp` instead of `cpp` . Using the basename solved the issue in our case and would be expected to deliver the correct behavior generally.
> Use basename only when checking for gfortran

- .github/common/install-python.sh
- .github/workflows/pymake-requests.yml
- autotest/test_cli_cmds.py
- autotest/test_requests.py
- pymake/pymake.py
- pymake/pymake_build_apps.py
Fix parsing command-line arguments when using make-program. 
Add test for ':' make-program target value.
> fix(cli): fix make-program to take ':' target value

- .github/workflows/main.yml
- .github/workflows/pymake-gcc.yml
- .github/workflows/pymake-linting-install.yml
- .github/workflows/pymake-requests.yml
- .github/workflows/pymake-rtd.yml
- autotest/pytest.ini
- autotest/test_cli_cmds.py
- autotest/test_gridgen.py
- autotest/test_mf2005.py
- autotest/test_mf6.py
- autotest/test_mf6_existing_meson.py
- autotest/test_mflgr.py
- autotest/test_mfnwt.py
- autotest/test_mfusg.py
- autotest/test_misc_programs.py
- autotest/test_mp6.py
- autotest/test_mp7.py
- autotest/test_mt3d.py
- autotest/test_requests.py
- autotest/test_seawat.py
- autotest/test_triangle_makefile.py
- pyproject.toml
- switch to [`awvwgk/setup-fortran`](https://github.com/awvwgk/setup-fortran) to install Intel compilers
- temporarily set `SETVARS_COMPLETED` and `CXX` manually until action patched
- use pytest temp dir fixtures in autotests
- add `pytest-dependency` to test dep group in `pyproject.toml`
- add `dependency` marker to `autotest/pytest.ini` to avoid warnings
> refactor(ci/tests): use awvwgk/setup-fortran, use pytest tempdirs

- .github/workflows/main.yml
- .github/workflows/pymake-gcc.yml
- .github/workflows/pymake-linting-install.yml
- .github/workflows/pymake-requests.yml
- .github/workflows/pymake-rtd.yml
* use `fortran-lang/setup-fortran` instead of `modflowpy/install-gfortran-action` (latter to be retired soon)
* use major version instead of full version tags for actions (less upkeep, fewer dependabot PRs)
* consolidate gcc test jobs in single matrix
* test gcc 11-13
* test python 3.11
> ci: use setup-fortran, use major version tags for actions

- .github/workflows/main.yml
- .github/workflows/pymake-gcc.yml
- .github/workflows/pymake-linting-install.yml
- .github/workflows/pymake-requests.yml
- .github/workflows/pymake-rtd.yml
- .gitignore
- pyproject.toml
* fix `awvwgk/setup-fortran` -> `fortran-lang/setup-fortran`
* remove `pytest-virtualenv` testing dependency
* add python 3.12 classifier in `pyproject.toml`
* update CI workflows to use python 3.12
* add IDE/venv folders to `.gitignore`
> refactor: support python3.12, various updates

- pymake/utils/_usgs_src_update.py
* replace functions are keyed by name as appears in usgsprograms.txt
* lookup did not account for 'dbl' or 'd' appended to program name
> fix(_usgs_src_update.py): fix function lookup in _build_replace()

- pymake/pymake.py
- pymake/utils/_compiler_switches.py
* remove ifort switches that issue warnings
* write absolute zip file path if using --zip argument
> refactor(pymake): limit zip file targets to new targets with --keep

- pymake/cmds/createjson.py
- pymake/utils/usgsprograms.py
* add appdir kwarg to be consistent with make-program
* add --appdir option to make-code-json cli to be consistent with make-program
> feat(export_json): add appdir kwarg

- .github/workflows/pymake-gcc.yml
- pyproject.toml
https://github.com/pytest-dev/pytest/releases/tag/8.1.0 broke some plugins and was yanked
> chore(dependencies): restrict yanked pytest version 8.1.0

- pymake/pymake_base.py
- pymake/utils/_usgs_src_update.py
- pyproject.toml
* extend default rules in `pyproject.toml`
* apply import sorting
* split or ignore comment lines where needed to fully observe E501
> chore(format): add isort rule, split long comment lines

- autotest/test_build.py
- autotest/test_gridgen.py
* fix gridgen gcc/g++ compile errors with `-Wl,-ld_classic` to select the classic linker
* https://forums.developer.apple.com/forums/thread/737707
* there are still failures building gridgen with intel on macos-14, it looks like a failure to find the appropriate header files &mdash; and there is some separate issue building GSFLOW
> ci(mac): use classic linker for gridgen with gnu compilers

- .github/workflows/main.yml
* gridgen build fails with newer versions of xcode command line tools
> ci(macos): use xcode clt 14.3.1 for intel c++ compiler compatibility

- autotest/ci_setup.py
- autotest/test_build.py
- autotest/test_cli_cmds.py
- autotest/test_gridgen.py
- autotest/test_mf6_existing_meson.py
- autotest/test_mp6.py
- autotest/test_mt3dusgs.py
- autotest/test_requests.py
- pymake/cmds/createjson.py
- pymake/cmds/mfpymakecli.py
- pymake/config.py
- pymake/pymake.py
- pymake/pymake_base.py
- pymake/pymake_build_apps.py
- pymake/pymake_parser.py
- pymake/utils/_compiler_language_files.py
- pymake/utils/_compiler_switches.py
- pymake/utils/_dag.py
- pymake/utils/_meson_build.py
- pymake/utils/_usgs_src_update.py
- pymake/utils/download.py
- pymake/utils/usgsprograms.py
- pyproject.toml
This PR refactors a few semi-related aspects:
- Revise strings and whitespace using a few methods with Ruff and manual edits
- Revise a few aspects of `pathlib.Path` -- these changes are added here to shorten some string formatting, but remain consistency throughout the code base
- Fix one more instance of removed `verbose` parameter in `_get_optlevel()`, similar to #199
- Apply Ruff [pyupgrade (UP)](https://docs.astral.sh/ruff/rules/#pyupgrade-up) rules
- Apply Ruff [section-underline-matches-section-length (D409)](https://docs.astral.sh/ruff/rules/section-underline-matches-section-length/#section-underline-matches-section-length-d409) rule
- Apply [Ruff-specific rules (RUF)](https://docs.astral.sh/ruff/rules/#ruff-specific-rules-ruf)
> refactor: clean-up strings and Path related aspects, add a few Ruff rules

- .github/workflows/ci.yml
- autotest/test_gridgen.py
Workaround oneAPI incompatibility with `ubuntu-24.04`
> ci: pin ubuntu-22.04 for now

- .github/workflows/pymake-linting-install.yml
- README.md
- docs/build_apps.md
- docs/getting_started.md
- pixi.toml
- pymake/cmds/createjson.py
- pymake/pymake_parser.py
- pymake/utils/_Popen_wrapper.py
- pymake/utils/_compiler_switches.py
- pymake/utils/usgsprograms.py
- pyproject.toml
Fix a few typos, add `check-spelling` pixi task that runs in CI.
> chore: fix typos and add codespell configuration
